# Generated by Django 2.0.5 on 2018-08-19 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_commnt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='commnt',
            new_name='Comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='commnt',
            new_name='comment',
        ),
    ]
